# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  # Repository: repository  # github repositories
  # Books: books  # 豆瓣书单
  # Links: links  # 友链
  About: about  # 关于

# http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# abbrlink config
abbrlink:
  alg: crc16 #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: Yu # 页面title
  favicon: /favicon.png
  board: <p>欢迎交流与分享经验!</p> <img src="/images/wechat.jpg"/> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: theme-black # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: true
  prev:
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
sidebar: right
widgets:
  # - board
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - tagcloud
  - archive

# widget behavior
archive_type: 'monthly' #'monthly'
show_count: true

# Fancybox
fancybox: true

# _hmt
baiduHmt: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.jpg
    title: 微信支付
  # 支付宝打赏
  alipay:
    qrcode: images/donate/alipayimg.jpg
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,qzone,wechat,tencent,douban,facebook,twitter,google,linkedin  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone,wechat,tencent,douban,,facebook,twitter,google,linkedin  # 移动端显示的分享图标

# Github
github:
  username: tangshiyu  # github username

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  enable: false
  type: valine  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan:
    uid: 1783844 # enter youyan uid
  livere:
    uid: MTAyMC8zNzA2NC8xMzYwMA== # enter youyan uid
  gitment:
    githubID: tangshiyu
    repo: https://github.com/tangshiyu.github.io
    ClientID: 439276f3e33e742fdf62
    ClientSecret: d55be60213a2977896e5767339537e48cccb34df
    lazy: true
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html

# douban 豆瓣书单
Api:
  - https://developers.douban.com/wiki/?title=book_v2 # 图书
  - https://developers.douban.com/wiki/?title=movie_v2 # 电影
books:
  - https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 # 个人书单列表
movies:
  - https://api.douban.com/v2/movie/in_theaters # 正在上映的电影
  - https://api.douban.com/v2/movie/coming_soon # 即将上映的电影
  - https://api.douban.com/v2/movie/subject/:id # 单个电影信息
  - https://api.douban.com/v2/movie/search?q={text} # 电影搜索

douban:
  user: lossingdawn # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数

# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  cnzz:
    enable: false  # cnzz统计
    web_id: 1273905585 # cnzz id
  leancloud:
    enable: false  # leancloud统计,网站需备案
    app_id: DEolJ5tYiyE6Ul2lHPEVqnqd-gzGzoHsz # leancloud <AppID>
    app_key: X8tvrNORow4igGI26PMF3tNI # leancloud <AppKey>

# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 150

# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计

# Plugins
plugins:
  google_analytics:  # enter the tracking ID for your Google Analytics
  google_site_verification:  # enter Google site verification code
  baidu_analytics: 3faed61998baf379e6a78a6b8ee3f44a # enter Baidu Analytics hash key
  tencent_analytics:

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:

# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/avatar.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Yu
  author_title: Software Developer
  author_description: 僧侣所修之道，即为禅定之道，非禅不智，非智不禅の
  location: GuangZhou, China
  follow: https://github.com/tangshiyu
  # Social Links
  social:
    links:
      # rss: atom.xml
      # github: https://github.com/tangshiyu
      # weibo: http://weibo.com/lossingdawnn
      # twitter: https://twitter.com/iwebued
      # facebook: /
      # dribbble: /
      # behance: https://www.behance.net/cofess 
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills
  skills:
    Golang: ★★★☆☆
    Python: ★★★☆☆
    Docker: ★★★☆☆
    Linux: ★★★☆☆
    K8s: ★★★☆☆
    Mongodb: ★★★☆☆
    Kafka: ★★★☆☆
    Zookeeper: ★★★☆☆
    Redis: ★★★☆☆
    HBase: ★★★☆☆
    Spark: ★★☆☆☆

  # My Personal Links
  links:
    # Github: https://github.com/tangshiyu
    # Blog: http://www.cnblogs.com/lossingdawn/
    # 微博: http://weibo.com/cofess
    # 花瓣: http://huaban.com/cofess
    # Behance: https://www.behance.net/cofess
  # My Personal Labels
  labels:
    - 后台开发
    - 微服务
    - Docker
    - 大数据
    - 云计算
    - Linux
  # My Personal Works
  # works:
  #  Tangshiyu:
  #    link: https://www.github.com/tangshiyu
  #    date: 2016
  # My Personal Projects
  projects:
    # cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
    # tangshiyu/hexo-theme-pure: https://github.com/tangshiyu/hexo-theme-dawn

# hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'


translate_title:
  translate_way: baidu    #google | baidu | youdao
  youdao_api_key: XXX
  youdao_keyfrom: XXX
  is_need_proxy: false     #true | false
  proxy_url: http://localhost:8123
  baidu_appid: '20190614000307344' # Your baidu_appid
  baidu_appkey: '9HUFhPabS8VVbT_zsrWz' # Your baidu_appkey

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: true
